
# TJL
# Dec 20, 2020

project:
  name:                 'plpro_DIALS_1p6A_ref2'
  target:               'PLpr'
  rawdata_dirs:
    - '/asap3/petra3/gpfs/p11/2020/data/11008472/raw'
  results_dir:          '/asap3/petra3/gpfs/p11/2020/data/11008472/scratch_cc'

refinement:
  method_name:          'dmpl2-redo'
  reduction_pipeline:   'plpro_DIALS_1p6A-dials'
  reference_pdb:        
    - '/asap3/petra3/gpfs/p11/2020/data/11008472/shared/PLpro_references/7nfv_altconformations_modified.pdb'
  free_flag_mtz:        '/asap3/petra3/gpfs/p11/2020/data/11008472/shared/PLpro_references/7nfv_rfree.mtz'
  place_waters:         False
  forcedown:            True

sql:
  host:                 'cfeld-vm05.desy.de'
  database:             'SARS_COV_2_Analysis_v2'
  user:                 'readWriter'
  password:             'sarsCovRW99!'
  connection_timeout:   60
  auth_plugin:          'mysql_native_password'
  autocommit:           True

slurm:
  partition:            'allrsv'
  reservation:          'covid'
#  partition:            'upex'


