
# TJL
# Dec 20, 2020

project:
  name:                 'plpro_DIALS_1p6A'
  target:               'PLpr'
  rawdata_dirs:
    - '/asap3/petra3/gpfs/p11/2020/data/11008472/raw'
  results_dir:          '/asap3/petra3/gpfs/p11/2020/data/11008472/scratch_cc'

xia2:
  pipeline:             'dials'
  d_min:                1.6

refinement:
  reference_pdb:        
    - '/asap3/petra3/gpfs/p11/2020/data/11008472/shared/PLpro_references/PLpro_wt_110920_VS.pdb'
  free_flag_mtz:        '/asap3/petra3/gpfs/p11/2020/data/11008472/shared/PLpro_references/PLPro_wt_110920_VS.mtz'
  place_waters:         False
  forcedown:            True

sql:
  host:                 'cfeld-vm05.desy.de'
  database:             'SARS_COV_2_Analysis_v2'
  user:                 'readWriter'
  password:             'sarsCovRW99!'
  connection_timeout:   60
  auth_plugin:          'mysql_native_password'
  autocommit:           True

slurm:
#  partition:            'allrsv'
#  reservation:          'covid'
  partition:            'cfel'


