
# TJL
# April 20, 2020

project:
  name:                 'DIALS_1p7A'
  pipeline:             'dials'
  rawdata_dirs:         ['/asap3/petra3/gpfs/p11/2020/data/11009999/raw',] 
  results_dir:          '/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc'
  reference_pdb:        '/asap3/petra3/gpfs/p11/2020/data/11009999/shared/mpro_references/SARS-COV-mpro_refine_110_edited.pdb'

xia2:
  d_min:                1.7

sql:
  host:                 'cfeld-vm05.desy.de'
  database:             'SARS_COV_2_Analysis_v2'
  user:                 'reader'
  password:             'sarsCovRead99!'
  connection_timeout:   60
  auth_plugin:          'mysql_native_password'
  autocommit:           True

slurm:
  partition:            'cfel'
#  partition:            'all'
#  reservation:          'covid'

