
# TJL
# April 20, 2020

project:
  name:                 'DMPL_test'
  rawdata_dirs:
    - '/asap3/petra3/gpfs/p11/2020/data/11009999/raw'
    - '/asap3/petra3/gpfs/p11/2020/data/11010091/raw'
  results_dir:          '/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc'

xia2:
  pipeline:             'dials'
  d_min:                1.7

refinement:
  reduction_pipeline:   'DIALS_1p7A-dials' # was project.pipeline_name
  place_waters:         True
  free_flag_mtz:        '/asap3/petra3/gpfs/p11/2020/data/11009999/shared/mpro_references/free_cor.mtz'
  reference_pdb:        
    - '/asap3/petra3/gpfs/p11/2020/data/11009999/shared/mpro_references/SARS-COV-mpro_refine_110_edited.pdb'
    - '/asap3/petra3/gpfs/p11/2020/data/11009999/shared/mpro_references/l8p22_09_001_002.pdb'

sql:
  host:                 'cfeld-vm05.desy.de'
  database:             'SARS_COV_2_Analysis_v2_test'
  user:                 'readWriter'
  password:             'sarsCovRW99!'
  connection_timeout:   60
  auth_plugin:          'mysql_native_password'
  autocommit:           True

slurm:
  partition:            'cfel'
#  partition:            'all'
#  reservation:          'covid'

