
# TJL
# April 20, 2020

project:
  name:                 'XDSv1_noice_dmpl'
  pipeline:             '3dii'
  pipeline_name:        'xds_reindex1_noice'
  rawdata_dirs:         
    - '/asap3/petra3/gpfs/p11/2020/data/11009999/raw'
    - '/asap3/petra3/gpfs/p11/2020/data/11010091/raw'
  results_dir:          '/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc'
  reference_pdb:        '/asap3/petra3/gpfs/p11/2020/data/11009999/shared/mpro_references/SARS-COV-mpro_refine_110_edited.pdb'

sql:
  host:                 'cfeld-vm05.desy.de'
  database:             'SARS_COV_2_Analysis_v2'
  user:                 'readWriter'
  password:             'sarsCovRW99!'
  connection_timeout:   60
  auth_plugin:          'mysql_native_password'
  autocommit:           True

slurm:
  partition:            'cfel'
  #reservation:          'covid'

