
# TJL
# April 20, 2020

project:
  name:                 'XDSv1_noice_dmpl2'
  rawdata_dirs:
    - '/asap3/petra3/gpfs/p11/2020/data/11009999/raw'
    - '/asap3/petra3/gpfs/p11/2020/data/11010091/raw'
    - '/asap3/petra3/gpfs/p11/2020/data/11010150/raw'
  results_dir:          '/asap3/petra3/gpfs/p11/2020/data/11009999/scratch_cc'


refinement:
  reduction_pipeline:   'xds_reindex1_noice'
  reference_pdb:        
    - '/asap3/petra3/gpfs/p11/2020/data/11009999/shared/mpro_references/SARS-COV-mpro_refine_223-edited.pdb'
    - '/asap3/petra3/gpfs/p11/2020/data/11009999/shared/mpro_references/beta101_refine_20_edited_edited.pdb'
  free_flag_mtz:        '/asap3/petra3/gpfs/p11/2020/data/11009999/shared/mpro_references/free_cor.mtz'
  place_waters:         False
  forcedown:            True

sql:
  host:                 'cfeld-vm05.desy.de'
  database:             'SARS_COV_2_Analysis_v2'
  user:                 'readWriter'
  password:             'sarsCovRW99!'
  connection_timeout:   60
  auth_plugin:          'mysql_native_password'
  autocommit:           True

slurm:
  partition:            'cfel'
#  partition:            'allrsv'
#  reservation:          'covid'

